config/routes.rb
Rails.application.routes.draw do
  resources :journals
  resources :losses
  resources :profits
  resources :loss_groups
  resources :profit_groups
  resources :debts
  resources :debt_groups
  resources :properties
  resources :property_groups
  get 'setting/index'
  get 'book/balance_sheet'
  get 'book/profit_loss_statement'

  devise_for :users

  root to: 'journals#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Accounts" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Accounts</a>
          <ul class="nav navbar-nav">
            <br>
            <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
            <% if user_signed_in? %> 
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "アカウント登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
          </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>

          <!-- start devise setting-->
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= devise_error_messages! %>
          <!-- end devise setting-->

          <%= yield %>

          <br>
          <br>

        </div>

        <% if user_signed_in? %> 
          <div class="col-lg-3">
            <div class="well sidebar-nav">
              <h3>メニュー</h3>
              <ul class="nav nav-list">
                <!-- 仕訳入力 -->
                <li>
                  <a data-toggle="collapse" data-parent="#accordion2" href="#collapseJournal">
                    <%= t('helpers.titles.journal') %>入力
                  </a>
                <div id="collapseJournal" class="accordion-body collapse" style="height: 0px;">
                  <div class="accordion-inner">
                    <%= link_to t('helpers.titles.pay'), new_journal_path( t: Journal::JOURNAL_TYPE_PAY ) %>
                    <%= link_to t('helpers.titles.payloan'), new_journal_path( t: Journal::JOURNAL_TYPE_PAYLOAN ) %>
                    <%= link_to t('helpers.titles.income'), new_journal_path( t: Journal::JOURNAL_TYPE_INCOME ) %>
                    <%= link_to t('helpers.titles.loan'), new_journal_path( t: Journal::JOURNAL_TYPE_LOAN ) %>
                    <%= link_to t('helpers.titles.repay'), new_journal_path( t: Journal::JOURNAL_TYPE_REPAY ) %>
                    <%= link_to t('helpers.titles.move'), new_journal_path( t: Journal::JOURNAL_TYPE_MOVE ) %>
                  </div>
                </div>
                </li>
                <!-- 取引履歴 -->
                <li><%= link_to t('helpers.titles.journallog'), journals_path %></li>
                <!-- 月次集計 -->
                <li>
                  <a data-toggle="collapse" data-parent="#accordion2" href="#collapseTotal">
                    <%= t('helpers.titles.total') %>
                  </a>
                <div id="collapseTotal" class="accordion-body collapse" style="height: 0px;">
                  <div class="accordion-inner">
                    <%= link_to t('helpers.titles.balance_sheet'), book_balance_sheet_path %>
                    <%= link_to "月次#{t('helpers.titles.profit_loss_statement')}", book_profit_loss_statement_path %>
                  </div>
                </div>
                </li>
                <!-- 設定 -->
                <li><%= link_to t('helpers.titles.setting'), setting_index_path %></li>
              </ul>
          </div><!--/span-->
        <% end %>
      </div><!--/row-->

    </div> <!-- /container -->

    <footer>
      <div class="row">
        <div class="col-xs-8 col-sm-7 col-md-5"><p>&copy; 2015 kbsh some rights reserved.</p></div>
        <div><iframe src="http://ghbtns.com/github-btn.html?user=kbsh&repo=rails_accounts&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe>
      </div>
    </footer>

  </body>
</html>